# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgamma_ <- function(x, theta) {
    .Call('frailtyr_dgamma_', PACKAGE = 'frailtyr', x, theta)
}

deriv_dgamma <- function(x, theta) {
    .Call('frailtyr_deriv_dgamma', PACKAGE = 'frailtyr', x, theta)
}

psi <- function(theta, N_dot, H_dot, frailty_distr) {
    .Call('frailtyr_psi', PACKAGE = 'frailtyr', theta, N_dot, H_dot, frailty_distr)
}

baseline_hazard_estimator <- function(X_, k_, d_, Y_, N_dot, beta, theta, frailty_distr) {
    .Call('frailtyr_baseline_hazard_estimator', PACKAGE = 'frailtyr', X_, k_, d_, Y_, N_dot, beta, theta, frailty_distr)
}

U_r <- function(R_, N_dot, I_, X_, H_, H_dot, beta, theta, beta_idx, frailty_distr) {
    .Call('frailtyr_U_r', PACKAGE = 'frailtyr', R_, N_dot, I_, X_, H_, H_dot, beta, theta, beta_idx, frailty_distr)
}

U_p <- function(R_, N_dot, I_, X_, H_, H_dot, beta, theta, theta_idx, tau_k, frailty_distr) {
    .Call('frailtyr_U_p', PACKAGE = 'frailtyr', R_, N_dot, I_, X_, H_, H_dot, beta, theta, theta_idx, tau_k, frailty_distr)
}

log_likelihood <- function(beta, theta, lambda, H_dot, I_, R_, X_, N_dot, frailty_distr) {
    .Call('frailtyr_log_likelihood', PACKAGE = 'frailtyr', beta, theta, lambda, H_dot, I_, R_, X_, N_dot, frailty_distr)
}

