# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgamma_c <- function(x, theta) {
    .Call('frailtyr_dgamma_c', PACKAGE = 'frailtyr', x, theta)
}

deriv_dgamma_c <- function(x, theta) {
    .Call('frailtyr_deriv_dgamma_c', PACKAGE = 'frailtyr', x, theta)
}

lt_dgamma_c <- function(p, s, theta) {
    .Call('frailtyr_lt_dgamma_c', PACKAGE = 'frailtyr', p, s, theta)
}

dlognormal_c <- function(x, theta) {
    .Call('frailtyr_dlognormal_c', PACKAGE = 'frailtyr', x, theta)
}

deriv_dlognormal_c <- function(x, theta) {
    .Call('frailtyr_deriv_dlognormal_c', PACKAGE = 'frailtyr', x, theta)
}

dinvgauss_c <- function(x, theta) {
    .Call('frailtyr_dinvgauss_c', PACKAGE = 'frailtyr', x, theta)
}

deriv_dinvgauss_c <- function(x, theta) {
    .Call('frailtyr_deriv_dinvgauss_c', PACKAGE = 'frailtyr', x, theta)
}

lt_dposstab_c <- function(p, s, theta) {
    .Call('frailtyr_lt_dposstab_c', PACKAGE = 'frailtyr', p, s, theta)
}

lt_dpvf_c <- function(p, s, theta) {
    .Call('frailtyr_lt_dpvf_c', PACKAGE = 'frailtyr', p, s, theta)
}

baseline_hazard_estimator <- function(X_, k_, d_, Y_, N_dot, beta, theta, frailty) {
    .Call('frailtyr_baseline_hazard_estimator', PACKAGE = 'frailtyr', X_, k_, d_, Y_, N_dot, beta, theta, frailty)
}

U_r <- function(X_, R_, I_, N_dot, H_, H_dot, beta, theta, beta_idx, frailty) {
    .Call('frailtyr_U_r', PACKAGE = 'frailtyr', X_, R_, I_, N_dot, H_, H_dot, beta, theta, beta_idx, frailty)
}

U_p <- function(X_, R_, I_, N_dot, H_, H_dot, beta, theta, theta_idx, frailty) {
    .Call('frailtyr_U_p', PACKAGE = 'frailtyr', X_, R_, I_, N_dot, H_, H_dot, beta, theta, theta_idx, frailty)
}

log_likelihood <- function(X_, R_, I_, N_dot, H_dot, lambda, beta, theta, frailty) {
    .Call('frailtyr_log_likelihood', PACKAGE = 'frailtyr', X_, R_, I_, N_dot, H_dot, lambda, beta, theta, frailty)
}

