# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgamma_c <- function(x, theta) {
    .Call('frailtyr_dgamma_c', PACKAGE = 'frailtyr', x, theta)
}

deriv_dgamma_c <- function(x, theta) {
    .Call('frailtyr_deriv_dgamma_c', PACKAGE = 'frailtyr', x, theta)
}

lt_dgamma_c <- function(m, s, theta) {
    .Call('frailtyr_lt_dgamma_c', PACKAGE = 'frailtyr', m, s, theta)
}

deriv_lt_dgamma_c <- function(m, s, theta) {
    .Call('frailtyr_deriv_lt_dgamma_c', PACKAGE = 'frailtyr', m, s, theta)
}

deriv_deriv_lt_dgamma_c <- function(m, s, theta) {
    .Call('frailtyr_deriv_deriv_lt_dgamma_c', PACKAGE = 'frailtyr', m, s, theta)
}

lt_dlognormal_c <- function(m, s, theta) {
    .Call('frailtyr_lt_dlognormal_c', PACKAGE = 'frailtyr', m, s, theta)
}

dlognormal_c <- function(x, theta) {
    .Call('frailtyr_dlognormal_c', PACKAGE = 'frailtyr', x, theta)
}

deriv_dlognormal_c <- function(x, theta) {
    .Call('frailtyr_deriv_dlognormal_c', PACKAGE = 'frailtyr', x, theta)
}

deriv_deriv_dlognormal_c <- function(x, theta) {
    .Call('frailtyr_deriv_deriv_dlognormal_c', PACKAGE = 'frailtyr', x, theta)
}

lt_dinvgauss_c <- function(m, s, theta) {
    .Call('frailtyr_lt_dinvgauss_c', PACKAGE = 'frailtyr', m, s, theta)
}

dinvgauss_c <- function(x, theta) {
    .Call('frailtyr_dinvgauss_c', PACKAGE = 'frailtyr', x, theta)
}

deriv_dinvgauss_c <- function(x, theta) {
    .Call('frailtyr_deriv_dinvgauss_c', PACKAGE = 'frailtyr', x, theta)
}

deriv_deriv_dinvgauss_c <- function(x, theta) {
    .Call('frailtyr_deriv_deriv_dinvgauss_c', PACKAGE = 'frailtyr', x, theta)
}

lt_dpvf_coef <- function(p, j, alpha) {
    .Call('frailtyr_lt_dpvf_coef', PACKAGE = 'frailtyr', p, j, alpha)
}

deriv_lt_dpvf_coef <- function(p, j, alpha) {
    .Call('frailtyr_deriv_lt_dpvf_coef', PACKAGE = 'frailtyr', p, j, alpha)
}

deriv_deriv_lt_dpvf_coef <- function(m, j, alpha) {
    .Call('frailtyr_deriv_deriv_lt_dpvf_coef', PACKAGE = 'frailtyr', m, j, alpha)
}

dpvf_c <- function(x, alpha) {
    .Call('frailtyr_dpvf_c', PACKAGE = 'frailtyr', x, alpha)
}

lt_dpvf_c <- function(m, s, alpha) {
    .Call('frailtyr_lt_dpvf_c', PACKAGE = 'frailtyr', m, s, alpha)
}

deriv_lt_dpvf_c <- function(m, s, alpha) {
    .Call('frailtyr_deriv_lt_dpvf_c', PACKAGE = 'frailtyr', m, s, alpha)
}

deriv_deriv_lt_dpvf_c <- function(m, s, alpha) {
    .Call('frailtyr_deriv_deriv_lt_dpvf_c', PACKAGE = 'frailtyr', m, s, alpha)
}

dposstab_c <- function(x, alpha) {
    .Call('frailtyr_dposstab_c', PACKAGE = 'frailtyr', x, alpha)
}

lt_dposstab_c <- function(p, s, alpha) {
    .Call('frailtyr_lt_dposstab_c', PACKAGE = 'frailtyr', p, s, alpha)
}

zeta <- function(s) {
    .Call('frailtyr_zeta', PACKAGE = 'frailtyr', s)
}

phi_c <- function(k, N_dot, H_dot, theta, frailty) {
    .Call('frailtyr_phi_c', PACKAGE = 'frailtyr', k, N_dot, H_dot, theta, frailty)
}

phi_prime_c <- function(k, N_dot, H_dot, theta, frailty, deriv_idx) {
    .Call('frailtyr_phi_prime_c', PACKAGE = 'frailtyr', k, N_dot, H_dot, theta, frailty, deriv_idx)
}

phi_prime_prime_c <- function(k, N_dot, H_dot, theta, frailty, deriv_idx_1, deriv_idx_2) {
    .Call('frailtyr_phi_prime_prime_c', PACKAGE = 'frailtyr', k, N_dot, H_dot, theta, frailty, deriv_idx_1, deriv_idx_2)
}

bh <- function(d_, R_star, K_, Y_, N_, N_dot, beta, theta, frailty, weights) {
    .Call('frailtyr_bh', PACKAGE = 'frailtyr', d_, R_star, K_, Y_, N_, N_dot, beta, theta, frailty, weights)
}

loglikelihood <- function(X_, K_, I_, phi_1_, lambda, beta) {
    .Call('frailtyr_loglikelihood', PACKAGE = 'frailtyr', X_, K_, I_, phi_1_, lambda, beta)
}

xi_beta <- function(X_, I_, H_, psi_, r) {
    .Call('frailtyr_xi_beta', PACKAGE = 'frailtyr', X_, I_, H_, psi_, r)
}

xi_theta <- function(phi_1_, phi_prime_1_, r) {
    .Call('frailtyr_xi_theta', PACKAGE = 'frailtyr', phi_1_, phi_prime_1_, r)
}

phi_k <- function(s, N_dot_, H_dot_, theta, frailty) {
    .Call('frailtyr_phi_k', PACKAGE = 'frailtyr', s, N_dot_, H_dot_, theta, frailty)
}

phi_prime_k <- function(s, theta_idx, N_dot_, H_dot_, theta, frailty) {
    .Call('frailtyr_phi_prime_k', PACKAGE = 'frailtyr', s, theta_idx, N_dot_, H_dot_, theta, frailty)
}

phi_prime_prime_k <- function(s, theta_idx_1, theta_idx_2, N_dot_, H_dot_, theta, frailty, kstart) {
    .Call('frailtyr_phi_prime_prime_k', PACKAGE = 'frailtyr', s, theta_idx_1, theta_idx_2, N_dot_, H_dot_, theta, frailty, kstart)
}

dH_dbeta <- function(s, d_, X_, K_, R_, R_dot_, R_star, phi_1_, phi_2_, phi_3_, Lambda, lambda, beta, theta, frailty) {
    .Call('frailtyr_dH_dbeta', PACKAGE = 'frailtyr', s, d_, X_, K_, R_, R_dot_, R_star, phi_1_, phi_2_, phi_3_, Lambda, lambda, beta, theta, frailty)
}

dH_dtheta <- function(d_, X_, K_, R_, R_dot_, R_star, phi_1_, phi_2_, phi_3_, phi_prime_1_, phi_prime_2_, Lambda, lambda, beta) {
    .Call('frailtyr_dH_dtheta', PACKAGE = 'frailtyr', d_, X_, K_, R_, R_dot_, R_star, phi_1_, phi_2_, phi_3_, phi_prime_1_, phi_prime_2_, Lambda, lambda, beta)
}

jacobian_beta_beta <- function(l, X_, K_, H_, phi_1_, phi_2_, phi_3_, dH_dbeta_, dH_dot_dbeta_) {
    .Call('frailtyr_jacobian_beta_beta', PACKAGE = 'frailtyr', l, X_, K_, H_, phi_1_, phi_2_, phi_3_, dH_dbeta_, dH_dot_dbeta_)
}

jacobian_beta_theta <- function(l, X_, K_, H_, phi_1_, phi_2_, phi_3_, phi_prime_1_, phi_prime_2_, dH_dtheta_, dH_dot_dtheta_) {
    .Call('frailtyr_jacobian_beta_theta', PACKAGE = 'frailtyr', l, X_, K_, H_, phi_1_, phi_2_, phi_3_, phi_prime_1_, phi_prime_2_, dH_dtheta_, dH_dot_dtheta_)
}

jacobian_theta_beta <- function(phi_1_, phi_2_, phi_prime_1_, phi_prime_2_, dH_dot_dbeta_) {
    .Call('frailtyr_jacobian_theta_beta', PACKAGE = 'frailtyr', phi_1_, phi_2_, phi_prime_1_, phi_prime_2_, dH_dot_dbeta_)
}

jacobian_theta_theta <- function(phi_1_, phi_2_, phi_prime_1_, phi_prime_2_, phi_prime_prime_1_, dH_dot_dtheta_) {
    .Call('frailtyr_jacobian_theta_theta', PACKAGE = 'frailtyr', phi_1_, phi_2_, phi_prime_1_, phi_prime_2_, phi_prime_prime_1_, dH_dot_dtheta_)
}

Q_beta <- function(X_, K_, H_, R_star, phi_1_, phi_2_, phi_3_, r) {
    .Call('frailtyr_Q_beta', PACKAGE = 'frailtyr', X_, K_, H_, R_star, phi_1_, phi_2_, phi_3_, r)
}

Q_theta <- function(H_, R_star, phi_1_, phi_2_, phi_prime_1_, phi_prime_2_) {
    .Call('frailtyr_Q_theta', PACKAGE = 'frailtyr', H_, R_star, phi_1_, phi_2_, phi_prime_1_, phi_prime_2_)
}

Ycal <- function(X_, R_star, Y_, psi_, beta) {
    .Call('frailtyr_Ycal', PACKAGE = 'frailtyr', X_, R_star, Y_, psi_, beta)
}

eta <- function(phi_1_, phi_2_, phi_3_) {
    .Call('frailtyr_eta', PACKAGE = 'frailtyr', phi_1_, phi_2_, phi_3_)
}

Upsilon <- function(X_, R_star, K_, R_dot_, eta_, Ycal_, beta) {
    .Call('frailtyr_Upsilon', PACKAGE = 'frailtyr', X_, R_star, K_, R_dot_, eta_, Ycal_, beta)
}

Omega <- function(X_, R_star, N_, R_dot_, eta_, Ycal_, beta) {
    .Call('frailtyr_Omega', PACKAGE = 'frailtyr', X_, R_star, N_, R_dot_, eta_, Ycal_, beta)
}

p_hat <- function(I_, Upsilon_, Omega_, N_tilde_) {
    .Call('frailtyr_p_hat', PACKAGE = 'frailtyr', I_, Upsilon_, Omega_, N_tilde_)
}

pi_r <- function(Q_, N_tilde_, p_hat) {
    .Call('frailtyr_pi_r', PACKAGE = 'frailtyr', Q_, N_tilde_, p_hat)
}

G_rl <- function(pi_r, pi_l, p_hat, Ycal_, N_) {
    .Call('frailtyr_G_rl', PACKAGE = 'frailtyr', pi_r, pi_l, p_hat, Ycal_, N_)
}

M_hat <- function(X_, R_star, N_, Y_, psi_, beta, Lambda) {
    .Call('frailtyr_M_hat', PACKAGE = 'frailtyr', X_, R_star, N_, Y_, psi_, beta, Lambda)
}

u_star <- function(pi_, p_hat, Ycal_, M_hat_) {
    .Call('frailtyr_u_star', PACKAGE = 'frailtyr', pi_, p_hat, Ycal_, M_hat_)
}

